server:
  port: 8091

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 数据库配置；启动时配置数据库资源信息
spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/w1_ai?stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
# MyBatis 配置【如需使用记得打开】
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  # config-location: classpath:/mybatis/config/mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名转换
ai:
  llm:
    api-key: sk-1e2d1a2adcae42e482f57ebcbca2e497
  embedding:
    api-key: sk-924a8ed2e50b43a188b7660aa2c1f93d
    base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

academic:
  s2:
    base-url: https://api.semanticscholar.org/graph/v1
    api-key: ""

redis:
  sdk:
    config:
      host: 127.0.0.1
      port: 16379
      database: 2