<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.winddol.ai</groupId>
        <artifactId>w1_ai</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>w1_ai-agent-librarian</artifactId>

    <dependencies>
        <dependency>
            <groupId>cn.winddol.ai</groupId>
            <artifactId>w1_ai-agent-framework</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.winddol.ai</groupId>
            <artifactId>w1_ai-shared</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.winddol.ai</groupId>
            <artifactId>w1_ai-paper</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.winddol.ai</groupId>
            <artifactId>w1_ai-domain</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>
    </dependencies>
</project>
